package com.ahamai.app.screens

import androidx.compose.animation.*
import androidx.compose.foundation.BorderStroke
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.lazy.rememberLazyListState
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.text.BasicTextField
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.ArrowBack
import androidx.compose.material.icons.filled.ArrowUpward
import androidx.compose.material.icons.filled.Check
import androidx.compose.material.icons.filled.Edit
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.text.font.FontFamily
import com.ahamai.app.ui.theme.JetBrainsMonoFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch

// Color palette matching the existing app style
private val sbDarkBg = Color(0xFF0C0C0E)
private val sbDarkRow = Color(0xFF161616)
private val sbDarkBorder = Color(0xFF1F1F1F)
private val sbLightRow = Color(0xFFF7F7F7)
private val sbLightBorder = Color(0xFFE6E6E6)

private data class SpecQuestion(
    val id: Int,
    val text: String,
    val options: List<String>?, // null = free text only
    val placeholder: String = "Type your answer...",
    val optional: Boolean = false
)

private val questions = listOf(
    SpecQuestion(1, "What do you want to build?", null, "Describe your idea..."),
    SpecQuestion(2, "What platform is this for?", listOf("Android App", "Website", "Script", "Game")),
    SpecQuestion(3, "Who will use it?", listOf("Just me", "Team", "Public")),
    SpecQuestion(4, "How should data be stored?", listOf("Offline only", "Cloud", "Both")),
    SpecQuestion(5, "Feature scope?", listOf("Basic", "Medium", "Full")),
    SpecQuestion(6, "Design style?", listOf("Clean minimal", "Colorful", "Card-based")),
    SpecQuestion(7, "Any specific requirements?", null, "Optional details...", optional = true)
)

private sealed class ChatItem {
    data class AgentMessage(val text: String) : ChatItem()
    data class UserAnswer(val text: String) : ChatItem()
    data class ChipOptions(val questionId: Int, val options: List<String>) : ChatItem()
    data class FreeInput(val questionId: Int, val placeholder: String, val optional: Boolean) : ChatItem()
    data class SpecPreview(val spec: String) : ChatItem()
}

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun SpecBuilderScreen(
    onBack: () -> Unit,
    onSpecApproved: (spec: String) -> Unit
) {
    val isDark = isSystemInDarkTheme()
    val scope = rememberCoroutineScope()

    val muted = if (isDark) Color(0xFF8E8E93) else Color(0xFF9CA3AF)
    val primaryText = if (isDark) Color(0xFFECECEC) else Color(0xFF141414)
    val border = if (isDark) sbDarkBorder else sbLightBorder
    val rowBg = if (isDark) sbDarkRow else sbLightRow

    var currentQuestion by remember { mutableStateOf(0) }
    val answers = remember { mutableStateMapOf<Int, String>() }
    var chatItems by remember { mutableStateOf<List<ChatItem>>(emptyList()) }
    var inputText by remember { mutableStateOf("") }
    var specGenerated by remember { mutableStateOf(false) }
    var generatedSpec by remember { mutableStateOf("") }
    var showingInput by remember { mutableStateOf(false) }
    val listState = rememberLazyListState()

    // Initialize with the first question
    LaunchedEffect(Unit) {
        delay(300)
        chatItems = listOf(
            ChatItem.AgentMessage("Let's build a spec for your project. I'll ask a few quick questions to understand what you need."),
        )
        delay(600)
        showNextQuestion(0, chatItems) { chatItems = it; showingInput = true }
    }

    // Auto-scroll to bottom
    LaunchedEffect(chatItems.size) {
        if (chatItems.isNotEmpty()) {
            delay(100)
            listState.animateScrollToItem(chatItems.size - 1)
        }
    }

    fun submitAnswer(answer: String) {
        if (answer.isBlank() && !questions[currentQuestion].optional) return
        val finalAnswer = answer.ifBlank { "None" }

        answers[currentQuestion] = finalAnswer
        showingInput = false
        chatItems = chatItems.filterNot {
            it is ChatItem.ChipOptions || it is ChatItem.FreeInput
        } + ChatItem.UserAnswer(finalAnswer)
        inputText = ""

        val nextQ = currentQuestion + 1
        if (nextQ < questions.size) {
            currentQuestion = nextQ
            scope.launch {
                delay(400)
                showNextQuestion(nextQ, chatItems) { chatItems = it; showingInput = true }
            }
        } else {
            // Generate spec
            scope.launch {
                delay(400)
                chatItems = chatItems + ChatItem.AgentMessage("Generating your spec...")
                delay(600)
                generatedSpec = generateSpec(answers)
                specGenerated = true
                chatItems = chatItems + ChatItem.SpecPreview(generatedSpec)
            }
        }
    }

    fun skipQuestion() {
        submitAnswer("")
    }

    Scaffold(
        topBar = {
            TopAppBar(
                windowInsets = WindowInsets.statusBars,
                navigationIcon = {
                    IconButton(onClick = onBack) {
                        Icon(Icons.Filled.ArrowBack, "Back", tint = primaryText, modifier = Modifier.size(22.dp))
                    }
                },
                title = {
                    Column {
                        Text("Spec Builder", fontSize = 16.sp, fontWeight = FontWeight.SemiBold, color = primaryText)
                        if (!specGenerated) {
                            Text(
                                "${currentQuestion + 1} of ${questions.size}",
                                fontSize = 11.sp, color = muted
                            )
                        }
                    }
                },
                colors = TopAppBarDefaults.topAppBarColors(containerColor = Color.Transparent)
            )
        },
        containerColor = MaterialTheme.colorScheme.background
    ) { padding ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(padding)
        ) {
            // Progress bar
            if (!specGenerated) {
                LinearProgressIndicator(
                    progress = { (currentQuestion.toFloat()) / questions.size },
                    modifier = Modifier
                        .fillMaxWidth()
                        .padding(horizontal = 20.dp)
                        .height(3.dp)
                        .clip(RoundedCornerShape(2.dp)),
                    color = if (isDark) Color(0xFF2A2A2A) else Color(0xFFD1D5DB),
                    trackColor = if (isDark) Color(0xFF141414) else Color(0xFFF3F4F6),
                )
                Spacer(Modifier.height(8.dp))
            }

            // Chat items
            LazyColumn(
                state = listState,
                modifier = Modifier
                    .weight(1f)
                    .fillMaxWidth()
                    .padding(horizontal = 16.dp),
                verticalArrangement = Arrangement.spacedBy(10.dp),
                contentPadding = PaddingValues(top = 12.dp, bottom = 12.dp)
            ) {
                items(chatItems.size) { index ->
                    val item = chatItems[index]
                    AnimatedVisibility(
                        visible = true,
                        enter = fadeIn() + slideInVertically { it / 3 }
                    ) {
                        when (item) {
                            is ChatItem.AgentMessage -> AgentBubble(item.text, primaryText, rowBg, isDark)
                            is ChatItem.UserAnswer -> UserBubble(item.text, primaryText, isDark)
                            is ChatItem.ChipOptions -> ChipOptionsRow(
                                options = item.options,
                                primaryText = primaryText,
                                muted = muted,
                                border = border,
                                isDark = isDark,
                                onSelect = { submitAnswer(it) }
                            )
                            is ChatItem.FreeInput -> {} // handled by bottom composer
                            is ChatItem.SpecPreview -> SpecPreviewCard(
                                spec = item.spec,
                                primaryText = primaryText,
                                muted = muted,
                                border = border,
                                rowBg = rowBg,
                                isDark = isDark,
                                onApprove = { onSpecApproved(generatedSpec) },
                                onEdit = {
                                    // Reset to start over
                                    specGenerated = false
                                    currentQuestion = 0
                                    answers.clear()
                                    chatItems = emptyList()
                                    scope.launch {
                                        delay(300)
                                        chatItems = listOf(
                                            ChatItem.AgentMessage("No problem, let's start fresh.")
                                        )
                                        delay(500)
                                        showNextQuestion(0, chatItems) { chatItems = it; showingInput = true }
                                    }
                                }
                            )
                        }
                    }
                }
            }

            // Bottom input area
            if (showingInput && !specGenerated) {
                val currentQ = questions[currentQuestion]
                Column(modifier = Modifier.fillMaxWidth().padding(horizontal = 12.dp, vertical = 8.dp)) {
                    if (currentQ.options != null) {
                        // Show "or type your own" hint for chip questions
                        Text(
                            "or type your own",
                            fontSize = 11.sp,
                            color = muted,
                            modifier = Modifier.padding(start = 16.dp, bottom = 4.dp)
                        )
                    }
                    Surface(
                        shape = RoundedCornerShape(24.dp),
                        color = rowBg,
                        border = BorderStroke(1.dp, border),
                        modifier = Modifier.fillMaxWidth()
                    ) {
                        Row(
                            modifier = Modifier.padding(start = 16.dp, end = 8.dp, top = 6.dp, bottom = 6.dp),
                            verticalAlignment = Alignment.CenterVertically
                        ) {
                            BasicTextField(
                                value = inputText,
                                onValueChange = { inputText = it },
                                modifier = Modifier.weight(1f).padding(vertical = 10.dp),
                                textStyle = LocalTextStyle.current.copy(fontSize = 14.sp, color = primaryText),
                                cursorBrush = SolidColor(primaryText),
                                decorationBox = { inner ->
                                    Box {
                                        if (inputText.isEmpty()) {
                                            Text(currentQ.placeholder, fontSize = 14.sp, color = muted)
                                        }
                                        inner()
                                    }
                                }
                            )
                            Spacer(Modifier.width(8.dp))
                            if (currentQ.optional && inputText.isBlank()) {
                                // Skip button for optional questions
                                Surface(
                                    shape = RoundedCornerShape(12.dp),
                                    color = Color.Transparent,
                                    modifier = Modifier.clickable { skipQuestion() }
                                ) {
                                    Text(
                                        "Skip",
                                        fontSize = 12.sp,
                                        color = muted,
                                        fontWeight = FontWeight.Medium,
                                        modifier = Modifier.padding(horizontal = 12.dp, vertical = 8.dp)
                                    )
                                }
                            }
                            val canSend = inputText.isNotBlank()
                            Box(
                                modifier = Modifier
                                    .size(32.dp)
                                    .clip(CircleShape)
                                    .background(
                                        if (canSend) MaterialTheme.colorScheme.primary
                                        else if (isDark) sbDarkBorder else Color(0xFFE0E0E6)
                                    )
                                    .clickable(enabled = canSend) { submitAnswer(inputText.trim()) },
                                contentAlignment = Alignment.Center
                            ) {
                                Icon(
                                    Icons.Filled.ArrowUpward, "Send",
                                    tint = if (canSend) MaterialTheme.colorScheme.onPrimary else muted,
                                    modifier = Modifier.size(17.dp)
                                )
                            }
                        }
                    }
                }
            }
        }
    }
}

private fun showNextQuestion(
    index: Int,
    currentItems: List<ChatItem>,
    update: (List<ChatItem>) -> Unit
) {
    val q = questions[index]
    val items = currentItems.toMutableList()
    items.add(ChatItem.AgentMessage(q.text))
    if (q.options != null) {
        items.add(ChatItem.ChipOptions(q.id, q.options))
    }
    items.add(ChatItem.FreeInput(q.id, q.placeholder, q.optional))
    update(items)
}

@Composable
private fun AgentBubble(text: String, primaryText: Color, rowBg: Color, isDark: Boolean) {
    Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.Start) {
        Surface(
            shape = RoundedCornerShape(topStart = 4.dp, topEnd = 18.dp, bottomEnd = 18.dp, bottomStart = 18.dp),
            color = rowBg,
            modifier = Modifier.widthIn(max = 300.dp)
        ) {
            Text(
                text,
                fontSize = 14.sp,
                color = primaryText,
                lineHeight = 20.sp,
                modifier = Modifier.padding(horizontal = 14.dp, vertical = 10.dp)
            )
        }
    }
}

@Composable
private fun UserBubble(text: String, primaryText: Color, isDark: Boolean) {
    Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.End) {
        Surface(
            shape = RoundedCornerShape(topStart = 18.dp, topEnd = 4.dp, bottomEnd = 18.dp, bottomStart = 18.dp),
            color = if (isDark) Color(0xFF141414) else Color(0xFFEBEBF0),
            modifier = Modifier.widthIn(max = 280.dp)
        ) {
            Text(
                text,
                fontSize = 14.sp,
                color = primaryText,
                lineHeight = 20.sp,
                modifier = Modifier.padding(horizontal = 14.dp, vertical = 10.dp)
            )
        }
    }
}

@Composable
private fun ChipOptionsRow(
    options: List<String>,
    primaryText: Color,
    muted: Color,
    border: Color,
    isDark: Boolean,
    onSelect: (String) -> Unit
) {
    Column(
        modifier = Modifier.fillMaxWidth().padding(start = 4.dp),
        verticalArrangement = Arrangement.spacedBy(6.dp)
    ) {
        options.forEach { option ->
            Surface(
                shape = RoundedCornerShape(14.dp),
                color = if (isDark) Color(0xFF141414) else Color(0xFFF4F4F4),
                border = BorderStroke(0.5.dp, border),
                modifier = Modifier.clickable { onSelect(option) }
            ) {
                Text(
                    option,
                    fontSize = 14.sp,
                    color = primaryText,
                    modifier = Modifier.padding(horizontal = 16.dp, vertical = 11.dp)
                )
            }
        }
    }
}

@Composable
private fun SpecPreviewCard(
    spec: String,
    primaryText: Color,
    muted: Color,
    border: Color,
    rowBg: Color,
    isDark: Boolean,
    onApprove: () -> Unit,
    onEdit: () -> Unit
) {
    Column(
        modifier = Modifier.fillMaxWidth(),
        verticalArrangement = Arrangement.spacedBy(10.dp)
    ) {
        // Spec content card
        Surface(
            shape = RoundedCornerShape(16.dp),
            color = rowBg,
            border = BorderStroke(1.dp, border),
            modifier = Modifier.fillMaxWidth()
        ) {
            Column(modifier = Modifier.padding(16.dp)) {
                Text(
                    "SPEC.md",
                    fontSize = 11.sp,
                    fontWeight = FontWeight.SemiBold,
                    color = muted,
                    fontFamily = JetBrainsMonoFamily,
                    letterSpacing = 1.sp
                )
                Spacer(Modifier.height(10.dp))
                Text(
                    spec,
                    fontSize = 13.sp,
                    color = primaryText,
                    lineHeight = 19.sp,
                    fontFamily = JetBrainsMonoFamily
                )
            }
        }

        // Action buttons
        Row(
            modifier = Modifier.fillMaxWidth(),
            horizontalArrangement = Arrangement.spacedBy(8.dp)
        ) {
            // Edit button
            Surface(
                shape = RoundedCornerShape(14.dp),
                color = if (isDark) Color(0xFF141414) else Color(0xFFF4F4F4),
                border = BorderStroke(0.5.dp, border),
                modifier = Modifier.weight(1f).clickable { onEdit() }
            ) {
                Row(
                    modifier = Modifier.padding(horizontal = 16.dp, vertical = 12.dp),
                    verticalAlignment = Alignment.CenterVertically,
                    horizontalArrangement = Arrangement.Center
                ) {
                    Icon(Icons.Filled.Edit, null, tint = muted, modifier = Modifier.size(15.dp))
                    Spacer(Modifier.width(6.dp))
                    Text("Start Over", fontSize = 13.sp, color = primaryText, fontWeight = FontWeight.Medium)
                }
            }

            // Approve button
            Surface(
                shape = RoundedCornerShape(14.dp),
                color = if (isDark) Color(0xFF141414) else Color(0xFFF4F4F4),
                border = BorderStroke(0.5.dp, border),
                modifier = Modifier.weight(1f).clickable { onApprove() }
            ) {
                Row(
                    modifier = Modifier.padding(horizontal = 16.dp, vertical = 12.dp),
                    verticalAlignment = Alignment.CenterVertically,
                    horizontalArrangement = Arrangement.Center
                ) {
                    Icon(Icons.Filled.Check, null, tint = Color(0xFF34C759), modifier = Modifier.size(15.dp))
                    Spacer(Modifier.width(6.dp))
                    Text("Approve & Build", fontSize = 13.sp, color = primaryText, fontWeight = FontWeight.Medium)
                }
            }
        }
    }
}

private fun generateSpec(answers: Map<Int, String>): String {
    val idea = answers[0] ?: "Untitled Project"
    val platform = answers[1] ?: "Not specified"
    val users = answers[2] ?: "Not specified"
    val storage = answers[3] ?: "Not specified"
    val scope = answers[4] ?: "Basic"
    val design = answers[5] ?: "Clean minimal"
    val requirements = answers[6]?.takeIf { it != "None" } ?: ""

    val sb = StringBuilder()
    sb.appendLine("# SPEC.md")
    sb.appendLine()
    sb.appendLine("## Project Overview")
    sb.appendLine(idea)
    sb.appendLine()
    sb.appendLine("## Target Platform")
    sb.appendLine(platform)
    sb.appendLine()
    sb.appendLine("## Target Users")
    sb.appendLine(users)
    sb.appendLine()
    sb.appendLine("## Data Strategy")
    sb.appendLine("- Storage: $storage")
    sb.appendLine()
    sb.appendLine("## Scope")
    sb.appendLine("- Complexity: $scope")
    sb.appendLine()
    sb.appendLine("## Design")
    sb.appendLine("- Style: $design")
    sb.appendLine()
    if (requirements.isNotBlank()) {
        sb.appendLine("## Additional Requirements")
        sb.appendLine(requirements)
        sb.appendLine()
    }
    sb.appendLine("## Implementation Notes")
    sb.appendLine("- Build this project step by step")
    sb.appendLine("- Create all necessary files from scratch")
    sb.appendLine("- Follow best practices for $platform development")
    sb.appendLine("- Keep the code clean and well-structured")

    return sb.toString().trim()
}
